In [1]:
import pandas as pd
import numpy as np

In [2]:
E=np.array([[1/4,1/4,1/4,0,1/4],[1/3,1/3,1/3,0,0],[1/4,1/4,1/4,1/4,0],[0,0,1/3,1/3,1/3],[1/3,0,0,1/3,1/3]])
df=pd.read_csv("Chambana_subnet.csv")
A=df.values[:,0:5]
I=df.values[:,5:10]
R=df.values[:,10:15]
S=df.values[:,15:20]
print(A)
A.shape


[[0.000625   0.0015     0.00040323 0.00061224 0.00324324]
 [0.00135417 0.00183333 0.00112903 0.00122449 0.00445946]
 [0.00166667 0.00183333 0.00201613 0.00122449 0.00391892]
 [0.00197917 0.00158333 0.00241936 0.00132653 0.00364865]
 [0.001875   0.00166667 0.00266129 0.00122449 0.00256757]
 [0.00208333 0.00191667 0.00306452 0.00142857 0.0027027 ]
 [0.00239583 0.00225    0.00346774 0.00163265 0.00283784]
 [0.00208333 0.00191667 0.00314516 0.00112245 0.00121622]
 [0.00197917 0.00133333 0.00233871 0.00142857 0.00040541]
 [0.00177083 0.00225    0.00209677 0.00163265 0.00135135]
 [0.00166667 0.0025     0.00193548 0.00142857 0.00162162]
 [0.001875   0.00275    0.00274194 0.00102041 0.0022973 ]
 [0.0015625  0.00233333 0.00258064 0.00091837 0.0022973 ]
 [0.00125    0.00241667 0.00233871 0.00081633 0.0027027 ]
 [0.00083333 0.00208333 0.00241936 0.00071429 0.00310811]
 [0.00083333 0.00166667 0.00282258 0.00061224 0.00324324]]


(16, 5)

In [3]:
def para_estimation(S,A,I,R,q,E,distr):
    AA=A[:,distr]
    II=I[:,distr]
    RR=R[:,distr]
    SS=S[:,distr]
    m=A.shape[1]
    n=len(AA)-1
    b=[]
    for i in range(n):
        b.append(AA[i+1]-AA[i])
    for i in range(n):
        b.append(II[i+1]-II[i])
    for i in range(n):
        b.append(RR[i+1]-RR[i])
    b=np.array(b)
    V=np.zeros((3*n,5))
    for i in range(n):
        s=0
        for j in range(m):
            s+=E[distr][j]*(A[i][j]+I[i][j])     
        V[i][0]=q*SS[i]*s
        V[i][1]=-AA[i]
        V[i][3]=-AA[i]
        V[i+n][0]=(1-q)*SS[i]*s
        V[i+n][1]=AA[i]
        V[i+n][2]=-II[i]
        V[i+2*n][2]=II[i]
        V[i+2*n][3]=AA[i]
        V[i+2*n][4]=-RR[i]
    B= np.linalg.pinv(V)
    return B.dot(b)

In [4]:
para_estimation(S,A,I,R,0.475,E,4)

array([0.13407854, 0.09432144, 0.10862008, 0.03166134, 0.00656331])